export const jargon_nouns = [
  "agent",
  "agents",
  "approach",
  "approaches",
  "attribute",
  "attributes",
  "channel",
  "cluster",
  "convolutional neural network",
  "convolutional neural networks",
  "data",
  "dataflow",
  "dataflows",
  "deep neural network",
  "deep neural networks",
  "design",
  "designs",
  "diagram",
  "diagrams",
  "event sequence",
  "event sequences",
  "exploration",
  "eye-tracking",
  "flow",
  "flows",
  "framework",
  "frameworks",
  "graph",
  "graphs",
  "image",
  "information",
  "machine learning",
  "map",
  "maps",
  "model",
  "models",
  "network",
  "networks",
  "neural network",
  "neural networks",
  "representation",
  "representations",
  "result",
  "results",
  "simulation",
  "simulations",
  "spatiotemporal",
  "studies",
  "study",
  "system",
  "systems",
  "tensor",
  "tensor field",
  "tensor fields",
  "tensors",
  "time-series",
  "topologies",
  "topology",
  "touch",
  "uncertainties",
  "uncertainty",
  "user",
  "users",
  "volume renderer",
  "workflow",
  "workflows",
  "volume rendering",
  "virtual reality",
];
